| | | |
|-|-|-|
|Top used Services.(Main Flow).| | |
|Steps|Action|Expected Result|
|1. Log into the AppKube Application using valid credentials.  2.. Navigate to the reporting module within the Application.                                          3. Select the option to access the Cloud Central Dashboard.|User logs in and navigates to the Cloud Central Dashboard.|Cloud Central Dashboard is displayed successfully.|
|1. Observe the Top used Services widget displaying the top 10 services with the highest usage across all accounts.  2. Click on the "View Details" button within the Top used Services widget.|Clicking on the "View Details" button should redirect the user to the Top used service page.|User should be redirected to the Top used service page displaying a list of top used services in a tabular format with relevant details.|
|1. On the Top used service page, identify the EC2 service from the list of services.  2. Click on the EC2 service action hyperlink.|The List of the top used services (Service Name, Service Count, Accounts count, Regions, Action.).Clicking on the EC2 service on (Action "view morw"). user should redirect  to the list of EC2 services page.|User should be redirected to the list of EC2 services page displaying details of each instance in a tabular format along with a search bar.|
|1. On the list of EC2 services page, identify a specific EC2 instance. 2. Click on the Instance ID of the identified instance.|On the list of EC2 instance (Instance ID, Instance Type, Availability Zone, Product Name, Instance State, Usage hours, Add-on, Overall Status of the instance.)  .Clicking on the Instance ID should redirect the user to the single instance page.|User should be redirected to the single instance page displaying details of the selected EC2 instance along with utilization graphs.|
|1. On the single instance page, user see the  CPU & memory utilization.                                                2. Verify the corresponding utilization graphs are displayed.|User see the  CPU & memory  utilization on the single instance page.|Utilization graphs  should be displayed on the . CPU and memory utilization graphs should show current and recommended instance utilization. |
|1. On the single instance page, user see the network Inbound and Outbound Traffic, and Disk read and write operation.                                                2. Verify the corresponding Data graphs are displayed.|User see the network Inbound and Outbound Traffic, and Disk read and write operation. on the single instance page.|Data graphs should be displayed on the . network Inbound and Outbound Traffic, and Disk read and write operation. graphs should show current and recommended instance Data. |
|1. Click on the "View all services" button on the Top used service page.|Clicking on the "View all services" button should redirect the user to the all services page.|User should be redirected to the all services page displaying overall services of all accounts.|
|1. On the all services page, identify the EC2 service.  2. Click on the EC2 service to view details.|Clicking on the EC2 service should redirect the user to the EC2 list page.|User should be redirected to the EC2 list page displaying details of all EC2 instances in a tabular format along with utilization graphs.|
|1. On the EC2 list page, identify a specific EC2 instance.  2. Click on the Instance ID of the identified instance.|Clicking on the Instance ID should redirect the user to the single instance page.|User should be redirected to the single instance page displaying details of the selected EC2 instance along with utilization graphs.|
| | | |
|Top used Services.(Alternative Flow).| | |
|Steps|Action|Expected Result|
|Attempt to access Cloud Central Dashboard.|Enter correct credentials and click on the Cloud Central Dashboard link.|Dashboard loads successfully displaying service details.|
|Encounter issues accessing Cloud Central Dashboard.|Enter correct credentials and click on the Cloud Central Dashboard link.|Error message appears indicating inability to access the dashboard.|
|Navigate to service details from Cloud Central Dashboard.|Upon successful access to the dashboard, click on a specific service to view its details.|Service details page loads displaying relevant information.|
|Encounter issues navigating through service details.|Click on a specific service to view its details.|Service details fail to load or display incomplete information.|
|Attempt to refresh the page upon encountering issues.|Refresh the page when issues occur while accessing the dashboard or navigating service details.|Page refreshes but issues persist, indicating a system-wide problem rather than a temporary glitch.|
|Check internet connection.|Verify internet connectivity before attempting to access the Cloud Central Dashboard.|Stable internet connection ensures smooth access to the dashboard and service details.|
|Contact support upon encountering issues.|If unable to access the dashboard or view service details, contact customer support.|Support team assists in resolving the issue, enabling the user to access the dashboard and view service details.|
